config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'solution#index'

  get 'lower_number', to: 'solution#lower_number'
  get 'geater_number', to: 'solution#geater_number'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/solution_controller.rb
class SolutionController < ApplicationController

  before_action :set_numbers

  def index
  end

  def lower_number
    $pubnub.publish(
      channel: "optimiza_chile",
      message: { title: 'Un chiste', text: @numbers }
    )
    @result = @numbers.sort[0]

    render :result, layout: false
  end

  def geater_number
    $pubnub.publish(
      channel: "optimiza_chile",
      message: { title: 'Un chiste', text: @numbers }
    )
    @result = @numbers.sort[-1]

    render :result, layout: false
  end


  private

  def set_numbers
    @numbers = [2, 4, 5, 6, 7, 84, 3, 34, 6, 2, 3, 45]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.pubnub.com/sdk/javascript/pubnub.4.8.0.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/solution/index.html.erb
<ul>
  <% @numbers.each do |number| %>
    <li><%= number %></li>
  <% end %>
</ul>

<p>Prueba:</p>
<div>
  <%= link_to 'Menor número', lower_number_path, remote: true %>
</div>
<div>
  <%= link_to 'Mayor número', geater_number_path, remote: true %>
</div>

<p>Resultado:
  <span id="result"></span>
</p>
<p>Los datos para la prueba se visualizan en tiempo real (abrir navegadores)</p>


app/views/solution/result.js.erb
$('#result').text("<%= @result %>")